services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    container_name: leakharvester_db
    ports:
      - "8123:8123" # HTTP
      - "9000:9000" # Native
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./data/clickhouse_data:/var/lib/clickhouse
      - ./data/clickhouse_logs:/var/log/clickhouse-server
    environment:
      - CLICKHOUSE_DB=vault
      - CLICKHOUSE_USER=leakharvester
      - CLICKHOUSE_PASSWORD=secret_password
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
    restart: unless-stopped
